تنسورفلو و نوع ورژن

In [3]:
import tensorflow as tf
import numpy as np


In [4]:
tf.__version__


'1.3.0'

In [5]:
print (tf.get_default_graph())

In [6]:
g = tf.Graph()

In [7]:
g

In [8]:
print (g is tf.get_default_graph())

False


In [9]:
with g.as_default():
    print(tf.get_default_graph)
    print(g)
    print (g is tf.get_default_graph())

<function get_default_graph at 0x7f530cdc7488>
True


# ساختمان داده‌ها در تنسورفلو

In [10]:
hello =  tf.constant("Hello")

In [11]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [12]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [14]:
# sess = tf.Session
# sess.close()

In [15]:
with tf.Session() as sess:
    result = sess.run(hello)



In [16]:
result

b'Hello'

In [17]:
result.decode()

'Hello'

In [18]:
a = tf.constant(2)

In [19]:
b = tf.constant(3)

In [20]:
print(a)

Tensor("Const_1:0", shape=(), dtype=int32)


In [21]:
type(b)

tensorflow.python.framework.ops.Tensor

In [22]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [23]:
result


5

In [24]:
vec_const = tf.fill((4,4),5)

In [25]:
vec_const


<tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>

In [26]:
vec_zero = tf.zeros((4,4))

In [27]:
vec_zero


<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [28]:
vec_one = tf.ones([4,4])

In [29]:
vec_randn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [30]:
vec_randu = tf.random_uniform((4,4),minval=0,maxval=10)

In [31]:
sess = tf.InteractiveSession()

In [32]:
print(sess.run(vec_one))

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [33]:
print(sess.run(vec_const))
print(sess.run(vec_randn))

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[-1.53253269  0.63349175  1.72002876  0.04570645]
 [-0.35166284  0.08273372 -1.81646943 -0.27978945]
 [-1.09671581  1.47954392 -1.12225306 -0.27304959]
 [ 0.26066524  0.26351094  1.88061643  0.17326474]]


In [34]:
print(vec_randu.eval())

[[ 4.73427057  8.2986784   1.34507537  9.368577  ]
 [ 8.91714478  9.4519701   1.66058421  6.9516921 ]
 [ 3.99688601  0.94851255  5.01123333  9.28719997]
 [ 4.3789506   9.03516769  7.89536953  7.65837193]]


In [35]:
print(vec_zero.get_shape())

(4, 4)


In [36]:
print(vec_zero.get_shape)

<bound method Tensor.get_shape of <tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>>


In [37]:
vec_zero.get_shape()


TensorShape([Dimension(4), Dimension(4)])

In [38]:
tf.matmul(vec_randn,vec_randu)

<tf.Tensor 'MatMul:0' shape=(4, 4) dtype=float32>

In [39]:
print(tf.matmul(vec_randn,vec_randu))

Tensor("MatMul_1:0", shape=(4, 4), dtype=float32)


In [40]:
sess.run(tf.matmul(vec_randn,vec_randu))

array([[ -2.22746634,  -8.77097034,   0.55561209,   9.95261002],
       [ -0.32966912,   6.49190712,  -1.00828838,   8.28403091],
       [  5.59730053,   9.32891178,   4.12536907,   7.14837933],
       [  8.55899811,   3.91858482,  10.91223621,   1.21482611]], dtype=float32)

In [41]:
tf.matmul(vec_randn,vec_randu).eval()


array([[-15.39171982,  -2.59704447,  -5.38378143,  -0.62618327],
       [  1.94189095,   7.16314411,   7.30985785,  -1.04807448],
       [  9.37228394,  10.75047493,  11.81439781,   9.93008232],
       [  0.02389002,  19.66356277,  18.12887764,   5.59103489]], dtype=float32)

# دو نوع تانسور اصلی در تنسورفلو: متغیر- جا نگهدار

In [42]:
var1 = tf.Variable(vec_randu)

In [43]:
print(var1)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [44]:
sess.run(var1)

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[Node: Variable/_12 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_4_Variable", _device="/job:localhost/replica:0/task:0/gpu:0"](Variable)]]
	 [[Node: Variable/_13 = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_4_Variable", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

In [47]:
init = tf.global_variables_initializer()

In [50]:
(sess.run(init))

In [51]:
print (sess.run(var1))

[[ 2.94398308  2.20178604  5.95515633  4.88446712]
 [ 4.52493763  7.17825174  6.58649826  6.92830181]
 [ 2.39242435  6.69046974  6.01014137  5.10750532]
 [ 4.34207678  1.0128653   5.53482294  1.86558843]]


In [52]:
ph = tf.placeholder(dtype=tf.float32,shape = (4,4))


In [53]:
print (sess.run(tf.matmul(ph, vec_randu),feed_dict={ph:np.random.uniform(1,5,(4,4))}))

[[ 47.85083771  41.23889542  67.42626953  36.25323105]
 [ 61.66528702  47.49541855  75.37542725  41.92906952]
 [ 70.95113373  67.59446716  98.27413177  48.38069534]
 [ 66.12447357  50.06512451  78.30632782  40.84401321]]


# مثال

# a * input + b

In [54]:
rand_a = np.random.uniform(0,100,(3,5))

In [55]:
rand_b = np.random.uniform(0,100,(1,5))

In [56]:
inp = np.random.exponential(0.5,(10,3))


In [57]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [58]:
add_op = a + b
mul_op = a * b

In [59]:
mul_res = sess.run(mul_op,feed_dict={a:inp , b:rand_a})

InvalidArgumentError: Incompatible shapes: [10,3] vs. [3,5]
	 [[Node: mul = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](_arg_Placeholder_1_0_0/_19, _arg_Placeholder_2_0_1/_21)]]

Caused by op 'mul', defined at:
  File "/home/hamim/anaconda3/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hamim/anaconda3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-58-5bf958d125ad>", line 2, in <module>
    mul_op = a * b
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 865, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 1088, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1449, in _mul
    result = _op_def_lib.apply_op("Mul", x=x, y=y, name=name)
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/hamim/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Incompatible shapes: [10,3] vs. [3,5]
	 [[Node: mul = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](_arg_Placeholder_1_0_0/_19, _arg_Placeholder_2_0_1/_21)]]


In [60]:
inp2 = np.random.exponential(0.5,(3,5))

In [61]:
mul_res = sess.run(mul_op,feed_dict={a:inp2 , b:rand_a})

In [62]:
mul_res

array([[ 14.86587715,  30.00419807,   8.29334068,  67.22679138,
         39.37446976],
       [ 13.03418636,  16.62958527,  24.31293678,  86.46768951,
          1.32994783],
       [ 17.03596878,   3.46450448,   5.77533245,   7.00837612,
         29.68091393]], dtype=float32)

In [63]:
mul_res = sess.run(tf.matmul(a,b),feed_dict={a:inp , b:rand_a})

In [64]:
mul_res

array([[ 102.9927063 ,   60.75608826,   55.87275696,  101.13074493,
          73.34843445],
       [ 139.20475769,   48.70947647,   78.3872757 ,  145.34858704,
          83.27038574],
       [  84.78031921,   22.87583351,   40.62470627,   74.6789093 ,
          57.57133865],
       [ 119.67531586,   21.6572361 ,   58.19064713,  108.03434753,
          76.30617523],
       [  62.18718719,   44.83158493,   35.78281784,   64.51737976,
          44.56070709],
       [ 139.05970764,   68.01812744,   73.7115097 ,  134.23817444,
          96.21659851],
       [ 163.42781067,   92.36228943,   90.81947327,  165.1975708 ,
         112.09246826],
       [  51.31695175,   28.25581741,   29.21293068,   53.34528351,
          34.01651382],
       [  76.0605545 ,   43.05213928,   44.40705872,   81.21360779,
          49.39165497],
       [ 152.38719177,   68.13273621,   85.24467468,  156.70530701,
          97.2650528 ]], dtype=float32)

In [65]:
add_res = sess.run(add_op,feed_dict={a:mul_res,b:np.repeat(rand_b,len(mul_res),axis=0)})

In [66]:
add_res

array([[ 162.67208862,  140.85220337,  149.49662781,  134.30300903,
         167.45275879],
       [ 198.88412476,  128.80560303,  172.01113892,  178.52084351,
         177.37471008],
       [ 144.45968628,  102.97195435,  134.24858093,  107.85116577,
         151.67565918],
       [ 179.35469055,  101.75335693,  151.81451416,  141.206604  ,
         170.41049194],
       [ 121.86656189,  124.92770386,  129.4066925 ,   97.68963623,
         138.66503906],
       [ 198.73907471,  148.11425781,  167.33538818,  167.41043091,
         190.32092285],
       [ 223.10717773,  172.45840454,  184.44334412,  198.36982727,
         206.1967926 ],
       [ 110.99632263,  108.35194397,  122.83679962,   86.51754761,
         128.12083435],
       [ 135.7399292 ,  123.14826202,  138.03092957,  114.38586426,
         143.49597168],
       [ 212.06655884,  148.22885132,  178.86854553,  189.87756348,
         191.36938477]], dtype=float32)

In [67]:
add_res = sess.run(tf.add(a,b),feed_dict={a:mul_res,b:np.repeat(rand_b,len(mul_res),axis=0)})

In [68]:
add_res

array([[ 162.67208862,  140.85220337,  149.49662781,  134.30300903,
         167.45275879],
       [ 198.88412476,  128.80560303,  172.01113892,  178.52084351,
         177.37471008],
       [ 144.45968628,  102.97195435,  134.24858093,  107.85116577,
         151.67565918],
       [ 179.35469055,  101.75335693,  151.81451416,  141.206604  ,
         170.41049194],
       [ 121.86656189,  124.92770386,  129.4066925 ,   97.68963623,
         138.66503906],
       [ 198.73907471,  148.11425781,  167.33538818,  167.41043091,
         190.32092285],
       [ 223.10717773,  172.45840454,  184.44334412,  198.36982727,
         206.1967926 ],
       [ 110.99632263,  108.35194397,  122.83679962,   86.51754761,
         128.12083435],
       [ 135.7399292 ,  123.14826202,  138.03092957,  114.38586426,
         143.49597168],
       [ 212.06655884,  148.22885132,  178.86854553,  189.87756348,
         191.36938477]], dtype=float32)

## مثال

In [69]:
arr = np.random.uniform(0,100,5)
print (arr)

[ 33.14672831   5.76269672  99.25921529  90.1916062   46.32328056]


In [70]:
print(sess.run(tf.cast(arr,tf.float16)))

[ 33.15625      5.76171875  99.25        90.1875      46.3125    ]


In [71]:
print(sess.run(tf.cast(arr,tf.int32)))

[33  5 99 90 46]


In [72]:
print(sess.run(tf.argmax(arr)))

2


In [74]:
arr = tf.cast(arr,tf.int32)
print(sess.run(tf.equal(arr,46)))

[False False False False  True]


In [75]:
print(sess.run(tf.less_equal(arr,50)))

[ True  True False False  True]


In [76]:
print(sess.run(tf.greater(arr,50)))

[False False  True  True False]
