# Tensor definition in PyTorch

Tensors are similar to numpy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch
import numpy

Construct a 5x3 matrix, uninitialized:

In [2]:
x = torch.Tensor(5, 3)
print(x)



 6.2185e-18  4.5811e-41  6.2185e-18
 4.5811e-41  6.3010e-36  6.3010e-36
 6.3010e-36  7.8003e-09  1.6131e-33
 6.3010e-36  6.3010e-36  6.3010e-36
 4.3300e-25  4.4340e-22  6.3010e-36
[torch.FloatTensor of size 5x3]



Get its size

In [3]:
print(x.size())

torch.Size([5, 3])


# operations


There are multiple syntaxes for operations. Let’s see addition as an example

Addition: syntax 1

In [4]:
y = torch.rand(5, 3)
print(x + y)


 0.0739  0.7897  0.7096
 0.7327  0.2834  0.7674
 0.7482  0.8103  0.5942
 0.2619  0.8479  0.0654
 0.3493  0.7726  0.8030
[torch.FloatTensor of size 5x3]



Addition: syntax 2

In [5]:
print(torch.add(x, y))


 0.0739  0.7897  0.7096
 0.7327  0.2834  0.7674
 0.7482  0.8103  0.5942
 0.2619  0.8479  0.0654
 0.3493  0.7726  0.8030
[torch.FloatTensor of size 5x3]



Addition: giving an output tensor

In [6]:
# adds x to y
y.add_(x)
print(y)


 0.0739  0.7897  0.7096
 0.7327  0.2834  0.7674
 0.7482  0.8103  0.5942
 0.2619  0.8479  0.0654
 0.3493  0.7726  0.8030
[torch.FloatTensor of size 5x3]



You can use standard numpy-like indexing with all bells and whistles!

In [7]:
print(x[:, 1])


 4.5811e-41
 6.3010e-36
 7.8003e-09
 6.3010e-36
 4.4340e-22
[torch.FloatTensor of size 5]



# Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

# Converting torch Tensor to numpy Array

In [8]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [9]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.

In [10]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


# Converting numpy Array to torch Tensor
See how changing the np array changed the torch Tensor automatically


In [11]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



## CUDA Tensors
All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

Tensors can be moved onto GPU using the .cuda function.

In [15]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    print(x+y)
    
    
    



 0.0739  0.7897  0.7096
 0.7327  0.2834  0.7674
 0.7482  0.8103  0.5942
 0.2619  0.8479  0.0654
 0.3493  0.7726  0.8030
[torch.cuda.FloatTensor of size 5x3 (GPU 0)]

